### ISSUE TITLE
Ability to support consul token based authentication

### ISSUE THREAD

**Issue by gshiva** [bwester/consulfs#8]
The current code does not support any form of authentication. We want the ability to supply the consul token to consulfs.

Addressed by PR #7

**Comment by bwester** [comment]
Thanks for contributing! This will be a useful addition.

What do you think about specifying the token in a config file?

**Comment by gshiva** [comment]
That would work too :)

I just wanted a quick fix :)

**Comment by bwester** [comment]
Well, the fix was quick, it just took me 3 years to get to it. My own usage of this tool has dropped off considerably lately. I added a `-token-file` option to specify a file to read the ACL secret token from. While I was at it, the `consulfs` command now also supports many of the same [environment variables](https://www.consul.io/commands#environment-variables) as the Consul agent for configuring the client. So another way to do the same thing would be to set `CONSUL_HTTP_TOKEN_FILE`. See reference: [`api.go`](https://github.com/hashicorp/consul/blob/v1.7.0/api/api.go#L24)
